import { ENTITLEMENT_KEYS } from "../keys";
import type { EntitlementKey } from "../types";

/** Server action namespace → entitlement (withServerActionGuard prefix). */
export const ACTION_NAMESPACE_IDS = {
  accountingFinance: "action:accountingFinance",
  admin: "action:admin",
  athleteCalendar: "action:athleteCalendar",
  athleteDetail: "action:athleteDetail",
  athleteOnboarding: "action:athleteOnboarding",
  athleteSelfProfile: "action:athleteSelfProfile",
  attendance: "action:attendance",
  audit: "action:audit",
  bodyMeasurement: "action:bodyMeasurement",
  coach: "action:coach",
  coachLifecycle: "action:coachLifecycle",
  coachPaymentRule: "action:coachPaymentRule",
  coachPayout: "action:coachPayout",
  coachProfile: "action:coachProfile",
  fieldTest: "action:fieldTest",
  finance: "action:finance",
  financeNote: "action:financeNote",
  injuryNote: "action:injuryNote",
  lesson: "action:lesson",
  location: "action:location",
  managementDirectory: "action:managementDirectory",
  notification: "action:notification",
  notificationPreference: "action:notificationPreference",
  operational: "action:operational",
  organization: "action:organization",
  payment: "action:payment",
  performance: "action:performance",
  permission: "action:permission",
  player: "action:player",
  privateLesson: "action:privateLesson",
  program: "action:program",
  queueAdmin: "action:queueAdmin",
  receivable: "action:receivable",
  schema: "action:schema",
  snapshot: "action:snapshot",
  superAdmin: "action:superAdmin",
  systemOps: "action:systemOps",
  team: "action:team",
  trainingLoadSurvey: "action:trainingLoadSurvey",
  trainingReport: "action:trainingReport",
  wellness: "action:wellness",
} as const;

export type ActionNamespaceMapKey = (typeof ACTION_NAMESPACE_IDS)[keyof typeof ACTION_NAMESPACE_IDS];

export const ACTION_NAMESPACE_ENTITLEMENT_MAP = {
  [ACTION_NAMESPACE_IDS.accountingFinance]: ENTITLEMENT_KEYS.finance,
  [ACTION_NAMESPACE_IDS.admin]: ENTITLEMENT_KEYS.core,
  [ACTION_NAMESPACE_IDS.athleteCalendar]: ENTITLEMENT_KEYS.athlete,
  [ACTION_NAMESPACE_IDS.athleteDetail]: ENTITLEMENT_KEYS.core,
  [ACTION_NAMESPACE_IDS.athleteOnboarding]: ENTITLEMENT_KEYS.core,
  [ACTION_NAMESPACE_IDS.athleteSelfProfile]: ENTITLEMENT_KEYS.athlete,
  [ACTION_NAMESPACE_IDS.attendance]: ENTITLEMENT_KEYS.core,
  [ACTION_NAMESPACE_IDS.audit]: ENTITLEMENT_KEYS.audit,
  [ACTION_NAMESPACE_IDS.bodyMeasurement]: ENTITLEMENT_KEYS.insightBodyMeasurements,
  [ACTION_NAMESPACE_IDS.coach]: ENTITLEMENT_KEYS.core,
  [ACTION_NAMESPACE_IDS.coachLifecycle]: ENTITLEMENT_KEYS.core,
  [ACTION_NAMESPACE_IDS.coachPaymentRule]: ENTITLEMENT_KEYS.finance,
  [ACTION_NAMESPACE_IDS.coachPayout]: ENTITLEMENT_KEYS.finance,
  [ACTION_NAMESPACE_IDS.coachProfile]: ENTITLEMENT_KEYS.core,
  [ACTION_NAMESPACE_IDS.fieldTest]: ENTITLEMENT_KEYS.insightFieldTests,
  [ACTION_NAMESPACE_IDS.finance]: ENTITLEMENT_KEYS.finance,
  [ACTION_NAMESPACE_IDS.financeNote]: ENTITLEMENT_KEYS.finance,
  [ACTION_NAMESPACE_IDS.injuryNote]: ENTITLEMENT_KEYS.core,
  [ACTION_NAMESPACE_IDS.lesson]: ENTITLEMENT_KEYS.core,
  [ACTION_NAMESPACE_IDS.location]: ENTITLEMENT_KEYS.core,
  [ACTION_NAMESPACE_IDS.managementDirectory]: ENTITLEMENT_KEYS.core,
  [ACTION_NAMESPACE_IDS.notification]: ENTITLEMENT_KEYS.communications,
  [ACTION_NAMESPACE_IDS.notificationPreference]: ENTITLEMENT_KEYS.communications,
  [ACTION_NAMESPACE_IDS.operational]: ENTITLEMENT_KEYS.core,
  [ACTION_NAMESPACE_IDS.organization]: ENTITLEMENT_KEYS.core,
  [ACTION_NAMESPACE_IDS.payment]: ENTITLEMENT_KEYS.finance,
  [ACTION_NAMESPACE_IDS.performance]: ENTITLEMENT_KEYS.insightPerformance,
  [ACTION_NAMESPACE_IDS.permission]: ENTITLEMENT_KEYS.core,
  [ACTION_NAMESPACE_IDS.player]: ENTITLEMENT_KEYS.core,
  [ACTION_NAMESPACE_IDS.privateLesson]: ENTITLEMENT_KEYS.privateLessons,
  [ACTION_NAMESPACE_IDS.program]: ENTITLEMENT_KEYS.core,
  [ACTION_NAMESPACE_IDS.queueAdmin]: ENTITLEMENT_KEYS.core,
  [ACTION_NAMESPACE_IDS.receivable]: ENTITLEMENT_KEYS.finance,
  [ACTION_NAMESPACE_IDS.schema]: ENTITLEMENT_KEYS.core,
  [ACTION_NAMESPACE_IDS.snapshot]: ENTITLEMENT_KEYS.core,
  [ACTION_NAMESPACE_IDS.superAdmin]: ENTITLEMENT_KEYS.core,
  [ACTION_NAMESPACE_IDS.systemOps]: ENTITLEMENT_KEYS.core,
  [ACTION_NAMESPACE_IDS.team]: ENTITLEMENT_KEYS.core,
  [ACTION_NAMESPACE_IDS.trainingLoadSurvey]: ENTITLEMENT_KEYS.athlete,
  [ACTION_NAMESPACE_IDS.trainingReport]: ENTITLEMENT_KEYS.insightTrainingReports,
  [ACTION_NAMESPACE_IDS.wellness]: ENTITLEMENT_KEYS.insightWellnessArchive,
} as const satisfies Record<ActionNamespaceMapKey, EntitlementKey>;
